apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liberary
  template:
    metadata:
      labels:
        app: liberary
    spec:
      containers:
      - image: okteto.dev/liberary:latest
        name: liberary
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mp3-juice.com"
        - name: Vless_UUID
          value: "782b0a36-ae13-4bc8-b7d2-31bf9acf1ae8"
        - name: Vless_Path
          value: "/YT87DI3W"
        - name: Vmess_UUID
          value: "782b0a36-ae13-4bc8-b7d2-31bf9acf1ae8"
        - name: Vmess_Path
          value: "/SDKJH4ty"
        - name: Share_Path
          value: "/Share302"
