apiVersion: apps/v1
kind: Deployment
metadata:
  name: racexsgvn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racexsgvn
  template:
    metadata:
      labels:
        app: racexsgvn
    spec:
      containers:
      - image: okteto.dev/racexsgvn:latest
        name: racexsgvn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "freemp3cloud.com"
        - name: Vless_UUID
          value: "d0d6652d-f213-467f-a089-eddc613b9a8d"
        - name: Vless_Path
          value: "/weud45y"
        - name: Vmess_UUID
          value: "d0d6652d-f213-467f-a089-eddc613b9a8d"
        - name: Vmess_Path
          value: "/hnirf5wt"
        - name: Share_Path
          value: "/Share342"
