apiVersion: apps/v1
kind: Deployment
metadata:
  name: heriuom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heriuom
  template:
    metadata:
      labels:
        app: heriuom
    spec:
      containers:
      - image: okteto.dev/heriuom:latest
        name: heriuom
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.anime-planet.com"
        - name: Vless_UUID
          value: "dbf1d0d5-6ee5-4e9a-81cb-2098ceb24a48"
        - name: Vless_Path
          value: "/avplkrgh"
        - name: Vmess_UUID
          value: "dbf1d0d5-6ee5-4e9a-81cb-2098ceb24a48"
        - name: Vmess_Path
          value: "/PREXCSZ"
        - name: Share_Path
          value: "/Share615"
